# GitHub Actions CI Workflow
# Triggered on every push and pull request
name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v

    - name: Run linter
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run ./...

    - name: Run tests with coverage
      run: go test -coverprofile=coverage.txt

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.txt
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: souravendra/distributed-rate-limiter-go-crispy-tribble
